import os
import mongoengine

"""
Django settings for sgc project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Permite rodar atrás de um proxy com prefixo de path (ex.: o proxy
# "/proxy/<porta>/" do ambiente Cloud9/codeweb). Sem a env var definida,
# o comportamento padrão (acesso direto) não muda.
FORCE_SCRIPT_NAME = os.environ.get("DJANGO_SCRIPT_NAME") or None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f7o3wfiz*7co-h$ci2c8-+g(%e^t_zm+5c5^tqxljb^!qmvq^&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
PROD_ENV = False
COMMENTS = True
ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = []

# Detecta o IP/hostname público da instância EC2 (quando disponível) para que o
# CsrfViewMiddleware aceite requisições feitas diretamente por esse endereço
# (ex.: acesso via https://<ip-publico> com TLS terminado por um proxy na frente
# do Django). Fora da EC2 (ex.: dev local) a chamada falha rapidamente e é
# ignorada.
import requests
EC2_PRIVATE_IP = None
try:
    EC2_PRIVATE_IP = requests.get(
        'http://169.254.169.254/latest/meta-data/public-hostname',
        timeout=0.5).text
    print(f"EC2 private IP: {EC2_PRIVATE_IP}")
except requests.exceptions.RequestException:
    print("Failed to get EC2 private IP, continuing without it.")
    pass

if EC2_PRIVATE_IP:
    ALLOWED_HOSTS.append(EC2_PRIVATE_IP)
    CSRF_TRUSTED_ORIGINS.append(f"https://{EC2_PRIVATE_IP}")
    CSRF_TRUSTED_ORIGINS.append(f"http://{EC2_PRIVATE_IP}")

# Este ambiente (Cloud9/codeweb) bloqueia o acesso a 169.254.169.254, então a
# detecção acima nunca encontra o IP. Para esses casos, permite informar as
# origens confiáveis explicitamente via variável de ambiente (ex. no .env):
# DJANGO_CSRF_TRUSTED_ORIGINS="https://52.6.118.200,http://52.6.118.200"
_extra_csrf_origins = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS")
if _extra_csrf_origins:
    for origin in _extra_csrf_origins.split(","):
        origin = origin.strip()
        if origin and origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

print(f"CSRF trusted origins: {CSRF_TRUSTED_ORIGINS}")
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'projeto',
]

MIDDLEWARE = [
    'sgc.middleware.StripDuplicateScriptNameMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sgc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sgc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if not PROD_ENV:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'django',
            'USER': 'rodrigo',
            'PASSWORD': '',
            'HOST': '',
            'PORT': '5432',
        }        
    }


if COMMENTS:
    mongo_host = '127.0.0.1' 
    mongo_port = 27017
    mongo_database = 'comments'
    mongoengine.connect(mongo_database, host=mongo_host, port=mongo_port)

    #DATABASES['mongodb'] = {
    #    'ENGINE': 'django_mongodb_engine',
    #    'NAME': 'comments',
    #    'USER': 'root',
    #    'PASSWORD': 'root',
    #    'HOST': 'localhost',
    #}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# Segue o mesmo prefixo de FORCE_SCRIPT_NAME, para que {% static %} gere o
# caminho correto quando rodando atrás do proxy (ver urls.py para a rota que
# efetivamente serve os arquivos, que usa o caminho sem o prefixo).
STATIC_URL = (FORCE_SCRIPT_NAME or "") + "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
