# Generated by Django 3.2.3 on 2021-06-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_projetotag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='fim',
            field=models.DateField(blank=True),
        ),
        migrations.DeleteModel(
            name='CoordenadorProjeto',
        ),
    ]
